extends: default
ignore-from-file: [.gitignore]
locale: en_US.UTF-8

rules:
  line-length:
    max: 140
  indentation:
    indent-sequences: false
  document-start:
    present: false
  comments:
    min-spaces-from-content: 1
